package db.armor.mail;

public class Chest {

  private static Object[][] chests = {
    {22060, "INV_Chest_Chain_03", "Beastmaster's Tunic"},
    {16950, "INV_Chest_Chain_11", "Breastplate of Ten Storms"},
    {22436, "INV_Chest_Chain_15", "Cryptstalker Tunic"},
    {16942, "INV_Chest_Chain_03", "Dragonstalker's Breastplate"},
    {20380, "INV_Chest_Plate08", "Dreamscale Breastplate"},
    {22464, "INV_Chest_Chain_15", "Earthshatter Tunic"},
    {16466, "INV_Chest_Chain_03", "Field Marshal's Chain Breastplate"},
    {16845, "INV_Chest_Chain_03", "Giantstalker's Breastplate"},
    {1981, "INV_Chest_Plate06", "Icemail Jerkin"},
    {22664, "INV_Chest_Plate09", "Icy Scale Breastplate"},
    {12641, "INV_Chest_Chain_07", "Invulnerable Mail"},
    {22191, "INV_Chest_Chain_17", "Obsidian Mail Tunic"},
    {19904, "INV_Chest_Plate08", "Runed Bloodstained Hauberk"},
    {11726, "INV_Chest_Chain_15", "Savage Gladiator Chain"},
    {21374, "INV_Chest_Chain_13", "Stormcaller's Hauberk"},
    {21370, "INV_Chest_Chain_04", "Striker's Hauberk"},
    {22102, "INV_Chest_Chain_11", "Vest of The Five Thunders"},
    {16565, "INV_Chest_Chain_11", "Warlord's Chain Chestpiece"},
    {16577, "INV_Chest_Chain_11", "Warlord's Mail Armor"},
    {19828, "INV_Chest_Fur", "Zandalar Augur's Hauberk"},
    {7759, "INV_Chest_Chain_11", "Archon Chestpiece"},
    {10784, "INV_Chest_Chain_05", "Atal'ai Breastplate"},
    {1488, "INV_Chest_Chain", "Avenger's Armor"},
    {16674, "INV_Chest_Chain_03", "Beaststalker's Tunic"},
    {15050, "INV_Chest_Plate06", "Black Dragonscale Breastplate"},
    {14611, "INV_Chest_Leather_05", "Bloodmail Hauberk"},
    {19690, "INV_Chest_Chain_14", "Bloodsoul Breastplate"},
    {15048, "INV_Chest_Chain_04", "Blue Dragonscale Breastplate"},
    {14536, "INV_Chest_Chain_14", "Bonebrace Hauberk"},
    {7133, "INV_Chest_Chain_07", "Brutal Hauberk"},
    {23088, "INV_Chest_Chain_08", "Chestguard of Undead Slaying"},
    {10764, "INV_Chest_Plate12", "Deathchill Armor"},
    {11926, "INV_Chest_Chain_07", "Deathdealer Breastplate"},
    {1717, "INV_Chest_Chain", "Double Link Tunic"},
    {8367, "INV_Chest_Chain_07", "Dragonscale Breastplate"},
    {13123, "INV_Chest_Chain_06", "Dreamwalker Armor"},
    {6972, "INV_Chest_Chain_07", "Fire Hardened Hauberk"},
    {9469, "INV_Chest_Chain_06", "Gahz'rilla Scale Armor"},
    {15045, "INV_Chest_Chain_06", "Green Dragonscale Breastplate"},
    {3844, "INV_Chest_Chain", "Green Iron Hauberk"},
    {7688, "INV_Chest_Plate15", "Ironspine's Ribcage"},
    {16425, "INV_Chest_Chain_06", "Knight-Captain's Chain Hauberk"},
    {23292, "INV_Chest_Chain_04", "Knight-Captain's Chain Hauberk"},
    {16525, "INV_Chest_Chain_04", "Legionnaire's Chain Breastplate"},
    {22874, "INV_Chest_Chain_04", "Legionnaire's Chain Hauberk"},
    {16522, "INV_Chest_Chain_16", "Legionnaire's Mail Chestpiece"},
    {22876, "INV_Chest_Chain_16", "Legionnaire's Mail Hauberk"},
    {3416, "INV_Chest_Chain", "Martyr's Chain"},
    {6627, "INV_Chest_Plate08", "Mutant Scale Breastplate"},
    {18530, "INV_Chest_Chain_12", "Ogre Forged Hauberk"},
    {6642, "INV_Chest_Chain_05", "Phantom Armor"},
    {1715, "INV_Chest_Chain_09", "Polished Jazeraint Armor"},
    {15047, "INV_Chest_Chain_06", "Red Dragonscale Breastplate"},
    {11820, "INV_Chest_Plate04", "Royal Decorated Armor"},
    {20478, "INV_Chest_Plate07", "Sandstalker Breastplate"},
    {10328, "INV_Chest_Chain_07", "Scarlet Chestpiece"},
    {2870, "INV_Chest_Plate15", "Shining Silver Breastplate"},
    {20479, "INV_Chest_Leather_02", "Spitfire Breastplate"},
    {6907, "INV_Shirt_06", "Tortoise Armor"},
    {16666, "INV_Chest_Chain_11", "Vest of Elements"},
    {12624, "INV_Chest_Chain_12", "Wildthorn Mail"},
    {15601, "INV_Chest_Chain_10", "Ancient Chestpiece"},
    {9836, "INV_Chest_Plate04", "Banded Armor"},
    {7914, "INV_Chest_Chain_14", "Barbaric Iron Breastplate"},
    {12108, "INV_Chest_Chain_16", "Basaltscale Armor"},
    {3283, "INV_Chest_Leather_04", "Battle Chain Tunic"},
    {6592, "INV_Chest_Chain_07", "Battleforge Armor"},
    {4082, "INV_Chest_Chain_12", "Blackforge Breastplate"},
    {4138, "INV_Chest_Chain_16", "Blackwater Tunic"},
    {4508, "INV_Chest_Plate08", "Blood-tinged Armor"},
    {14798, "INV_Chest_Chain_07", "Bloodlust Breastplate"},
    {15488, "INV_Chest_Chain_07", "Bloodspattered Surcoat"},
    {15609, "INV_Chest_Chain_05", "Bonelink Armor"},
    {3306, "INV_Chest_Cloth_06", "Brackwater Vest"},
    {9928, "INV_Chest_Plate15", "Brigade Breastplate"},
    {2989, "INV_Chest_Chain_06", "Burnished Tunic"},
    {9765, "INV_Chest_Chain_05", "Cadet Vest"},
    {7486, "INV_Chest_Plate07", "Captain's Breastplate"},
    {7538, "INV_Chest_Chain_05", "Champion's Armor"},
    {15479, "INV_Chest_Chain_16", "Charger's Armor"},
    {6721, "INV_Chest_Leather_05", "Chestplate of Kor"},
    {6411, "INV_Chest_Plate08", "Chief Brigadier Armor"},
    {3471, "INV_Chest_Chain", "Copper Chain Vest"},
    {10193, "INV_Chest_Chain_06", "Crusader's Armor"},
    {3330, "INV_Chest_Chain", "Dargol's Hauberk"},
    {11606, "INV_Chest_Chain_16", "Dark Iron Mail"},
    {9663, "INV_Chest_Chain_16", "Dawnrider's Chestpiece"},
    {6580, "INV_Chest_Chain_04", "Defender Tunic"},
    {1275, "INV_Chest_Chain", "Deputy Chain Coat"},
    {1677, "INV_Chest_Chain_06", "Drake-scale Vest"},
    {8265, "INV_Chest_Chain_17", "Ebonhold Armor"},
    {14760, "INV_Chest_Chain_15", "Enduring Breastplate"},
    {10230, "INV_Chest_Plate16", "Engraved Breastplate"},
    {7229, "INV_Chest_Chain_12", "Explorer's Vest"},
    {1273, "INV_Chest_Plate07", "Forest Chain"},
    {15631, "INV_Chest_Chain_10", "Formidable Chestpiece"},
    {9818, "INV_Chest_Chain", "Fortified Chain"},
    {6773, "INV_Chest_Chain_07", "Gelkis Marauder Chain"},
    {4071, "INV_Chest_Plate16", "Glimmering Mail Breastplate"},
    {3845, "INV_Chest_Chain_06", "Golden Scale Cuirass"},
    {15514, "INV_Chest_Chain", "Grunt's Chestpiece"},
    {15622, "INV_Chest_Plate06", "Gryphon Mail Breastplate"},
    {15076, "INV_Chest_Chain_15", "Heavy Scorpid Vest"},
    {8303, "INV_Chest_Plate14", "Hero's Breastplate"},
    {9650, "INV_Chest_Plate16", "Honorguard Chestpiece"},
    {14744, "INV_Chest_Chain_15", "Hulking Chestguard"},
    {3053, "INV_Chest_Chain", "Humbert's Chestpiece"},
    {4448, "INV_Misc_MonsterSpiderCarapace_01", "Husk of Naraxis"},
    {15660, "INV_Chest_Plate01", "Impenetrable Breastplate"},
    {6336, "INV_Chest_Chain", "Infantry Tunic"},
    {6731, "INV_Chest_Plate05", "Ironforge Breastplate"},
    {3166, "INV_Chest_Chain", "Ironheart Chain"},
    {15640, "INV_Chest_Plate08", "Ironhide Breastplate"},
    {15827, "INV_Chest_Chain_04", "Jadescale Breastplate"},
    {9897, "INV_Chest_Chain_09", "Jazeraint Chestguard"},
    {14779, "INV_Chest_Cloth_02", "Khan's Chestpiece"},
    {7454, "INV_Chest_Plate04", "Knight's Breastplate"},
    {3049, "INV_Chest_Chain_06", "Lambent Scale Breastplate"},
    {914, "INV_Chest_Chain", "Large Ogre Chain Armor"},
    {10077, "INV_Chest_Plate15", "Lord's Breastplate"},
    {15669, "INV_Chest_Chain_07", "Magnificent Breastplate"},
    {4074, "INV_Chest_Chain_13", "Mail Combat Armor"},
    {15567, "INV_Chest_Plate04", "Marauder's Tunic"},
    {10266, "INV_Chest_Plate16", "Masterwork Breastplate"},
    {15650, "INV_Chest_Leather_07", "Merciless Surcoat"},
    {10157, "INV_Chest_Chain_07", "Mercurial Breastplate"},
    {8126, "INV_Chest_Chain_06", "Myrmidon's Breastplate"},
    {5755, "INV_Chest_Plate04", "Onyx Shredder Plate"},
    {3733, "INV_Chest_Chain", "Orcish War Chain"},
    {10118, "INV_Chest_Chain_10", "Ornate Breastplate"},
    {15500, "INV_Chest_Chain_04", "Outrunner's Chestguard"},
    {7418, "INV_Chest_Plate01", "Phalanx Breastplate"},
    {15557, "INV_Chest_Chain_12", "Pillager's Chestguard"},
    {11194, "INV_Chest_Chain_07", "Prismscale Hauberk"},
    {14789, "INV_Chest_Leather_08", "Protector Breastplate"},
    {12415, "INV_Chest_Plate16", "Radiant Breastplate"},
    {9783, "INV_Chest_Chain_07", "Raider's Chestpiece"},
    {14768, "INV_Chest_Chain_07", "Ravager's Armor"},
    {17777, "INV_Chest_Chain_07", "Relentless Chain"},
    {9866, "INV_Chest_Chain_12", "Renegade Chestguard"},
    {2864, "INV_Chest_Plate03", "Runed Copper Breastplate"},
    {19128, "INV_Chest_Chain_13", "Seared Mail Vest"},
    {15524, "INV_Chest_Leather_04", "Sentry's Surcoat"},
    {2869, "INV_Chest_Chain_09", "Silvered Bronze Breastplate"},
    {6180, "INV_Chest_Chain_12", "Slarkskin"},
    {14751, "INV_Chest_Chain_07", "Slayer's Surcoat"},
    {6545, "INV_Chest_Chain_16", "Soldier's Armor"},
    {15578, "INV_Chest_Plate16", "Sparkleshell Breastplate"},
    {15518, "INV_Chest_Chain_17", "Spiked Chain Breastplate"},
    {12049, "INV_Chest_Chain_16", "Splintsteel Armor"},
    {15591, "INV_Chest_Chain_04", "Steadfast Breastplate"},
    {7963, "INV_Chest_Plate05", "Steel Breastplate"},
    {15546, "INV_Chest_Cloth_06", "Thick Scale Breastplate"},
    {8203, "INV_Chest_Leather_02", "Tough Scorpid Breastplate"},
    {15680, "INV_Chest_Plate16", "Triumphant Chestpiece"},
    {8189, "INV_Chest_Chain_12", "Turtle Scale Breastplate"},
    {21320, "INV_Chest_Chain_16", "Vest of the Den Watcher"},
    {2977, "INV_Chest_Chain_09", "Veteran Armor"},
    {6502, "INV_Chest_Chain_04", "Violet Scale Armor"},
    {14730, "INV_Chest_Chain", "War Paint Chestpiece"},
    {15487, "INV_Chest_Chain_07", "War Torn Tunic"},
    {9957, "INV_Chest_Samurai", "Warmonger's Chestpiece"},
    {2965, "INV_Chest_Chain", "Warrior's Tunic"},
    {14811, "INV_Chest_Chain_05", "Warstrike Chestguard"},
    {6195, "INV_Chest_Chain", "Wax-polished Armor"},
    {15536, "INV_Chest_Plate04", "Wicked Chain Chestpiece"},
    {7336, "INV_Chest_Chain", "Wildwood Chain"},
    {15787, "INV_Chest_Chain_16", "Willow Band Hauberk"},
    {2417, "INV_Chest_Plate12", "Augmented Chain Vest"},
    {10656, "INV_Chest_Chain", "Barkmail Vest"},
    {2423, "INV_Chest_Plate13", "Brigandine Vest"},
    {847, "INV_Chest_Chain", "Chainmail Armor"},
    {2109, "INV_Chest_Chain", "Frostmane Chain Vest"},
    {4922, "INV_Chest_Chain", "Jagged Chain Vest"},
    {2398, "INV_Chest_Chain", "Light Chain Armor"},
    {2392, "INV_Chest_Chain", "Light Mail Armor"},
    {2898, "INV_Chest_Chain", "Mountaineer Chestpiece"},
    {2153, "INV_Chest_Chain_09", "Polished Scale Vest"},
    {2866, "INV_Chest_Chain_08", "Rough Bronze Cuirass"},
    {10421, "INV_Chest_Chain", "Rough Copper Vest"},
    {3273, "INV_Chest_Chain", "Rugged Mail Vest"},
    {2386, "INV_Chest_Chain", "Rusted Chain Vest"},
    {285, "INV_Chest_Chain_09", "Scalemail Vest"},
    {3151, "INV_Chest_Chain", "Siege Brigade Vest"},
    {2379, "INV_Chest_Chain", "Tarnished Chain Vest"},
    {3815, "INV_Chest_Chain", "Double Mail Vest"},
    {2656, "INV_Chest_Chain", "Flimsy Chain Vest"},
    {1745, "INV_Chest_Chain", "Laced Mail Vest"},
    {3999, "INV_Chest_Chain_05", "Laminated Scale Armor"},
    {1753, "INV_Chest_Chain", "Linked Chain Vest"},
    {2648, "INV_Chest_Chain", "Loose Chain Vest"},
    {4007, "INV_Chest_Chain_13", "Overlinked Chain Armor"},
    {1761, "INV_Chest_Chain", "Reinforced Chain Vest"},
    {1737, "INV_Chest_Chain", "Worn Mail Vest"}
  };
  
  public static int[] getIDs() {
    int[] res = new int[chests.length];
    for (int i = 0; i < chests.length; i++)
      res[i] = (int)chests[i][0];
    return res;
  }
  
  public static String[] getIcons() {
    String[] res = new String[chests.length];
    for (int i = 0; i < chests.length; i++)
      res[i] = (String)chests[i][1];
    return res;
  }
  
  public static String[] getNames() {
    String[] res = new String[chests.length];
    for (int i = 0; i < chests.length; i++)
      res[i] = (String)chests[i][2];
    return res;
  }
  
  public static void main(String[] args) {
    int[] t1 = getIDs();
    String[] t2 = getIcons();
    String[] t3 = getNames();
    for (int i = 0; i < t1.length; i++)
      System.out.println(t1[i] + ", " + t2[i] + ", " + t3[i]);
  }
}
